# Generated by Django 3.2.9 on 2022-03-06 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSatori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('email', models.EmailField(max_length=255, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=15, verbose_name='Telefono')),
                ('comment', models.TextField(blank=True, max_length=255, verbose_name='Comentario')),
            ],
            options={
                'verbose_name': 'Comentario',
                'verbose_name_plural': 'Comentarios',
            },
        ),
    ]
