# Generated by Django 3.2.9 on 2022-03-06 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moStartDate', models.DateField(verbose_name='Fecha Inicio')),
                ('moFinishDate', models.DateField(verbose_name='Fecha Fin')),
                ('moType', models.CharField(max_length=255, verbose_name='Tipo de Mensualidad')),
            ],
            options={
                'verbose_name': 'Mensualidades',
            },
        ),
    ]
