# Generated by Django 3.2.9 on 2022-03-07 02:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moStartDate', models.DateField(verbose_name='Fecha Inicio')),
                ('moFinishDate', models.DateField(verbose_name='Fecha Fin')),
                ('moType', models.CharField(choices=[('semanal', 'Semanal'), ('quincenal', 'Quincenal'), ('mensual', 'Mensual')], max_length=255, verbose_name='Tipo de Mensualidad')),
                ('moPrice', models.FloatField(verbose_name='Precio Mensualidad')),
                ('user', models.ForeignKey(default='', help_text='Estudiante', on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Mensualidad',
                'verbose_name_plural': 'Mensualidades',
            },
        ),
    ]
