# Generated by Django 3.2.9 on 2022-09-22 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monthly_payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlypayment',
            name='moType',
            field=models.CharField(choices=[('mensual completo', 'Mensual Completo'), ('mensual lunes a viernes', 'Mensual Lunes a Viernes'), ('solo sabados', 'Solo Sabados'), ('tiquetera 10 clases', 'Tiquetera 10 Clases')], max_length=255, verbose_name='Tipo de Mensualidad'),
        ),
    ]
