# Generated by Django 3.2.9 on 2022-03-08 01:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opComment', models.CharField(max_length=255, verbose_name='Comentario')),
                ('opQualification', models.CharField(choices=[('malo', 'Malo'), ('regular', 'Regular'), ('bueno', 'Bueno'), ('muy bueno', 'Muy Bueno'), ('excelente', 'Excelente')], max_length=255, verbose_name='Calificación de la lección')),
                ('lesson', models.ForeignKey(default='', help_text='Leccion', on_delete=django.db.models.deletion.CASCADE, related_name='Lecciones', to='lessons.lesson', verbose_name='Leccion')),
                ('user', models.ForeignKey(default='', help_text='Estudiante', on_delete=django.db.models.deletion.CASCADE, related_name='Usuarios', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Reseña',
                'verbose_name_plural': 'Reseñas',
            },
        ),
    ]
