# Generated by Django 3.2.9 on 2022-03-07 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opComment', models.CharField(max_length=255, verbose_name='Comentario')),
                ('opQualification', models.CharField(choices=[('malo', 'Malo'), ('regular', 'Regular'), ('bueno', 'Bueno'), ('muy bueno', 'Muy Bueno'), ('excelente', 'Excelente')], max_length=255, verbose_name='Calificación de la lección')),
                ('lesson', models.ForeignKey(default='', help_text='Estudiante', on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='lessons.lesson', verbose_name='lesson')),
            ],
            options={
                'verbose_name': 'Reseña',
                'verbose_name_plural': 'Reseñas',
            },
        ),
    ]
