# Generated by Django 3.2.9 on 2022-03-06 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coTitle', models.CharField(max_length=255, verbose_name='Titulo')),
                ('coDescription', models.CharField(max_length=255, verbose_name='Descripción')),
                ('coImage', models.CharField(max_length=255, verbose_name='Imagen')),
                ('coPrice', models.FloatField(verbose_name='Precio')),
                ('coInstructor', models.CharField(default='', max_length=255, verbose_name='Instructor')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paDate', models.DateField(verbose_name='Fecha de Pago')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='courses.course', verbose_name='Curso')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
            },
        ),
    ]
