# Generated by Django 3.2.9 on 2022-03-06 19:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.ForeignKey(help_text='Categoria del curso', on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='categories.category', verbose_name='Categoria'),
        ),
        migrations.AddField(
            model_name='course',
            name='members',
            field=models.ManyToManyField(through='courses.Payment', to=settings.AUTH_USER_MODEL),
        ),
    ]
