# Generated by Django 3.2.9 on 2022-02-14 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='coDescription',
            field=models.CharField(max_length=255, verbose_name='Descripción'),
        ),
    ]
