# Generated by Django 3.2.9 on 2022-03-15 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='coCalendar',
            field=models.CharField(default='', max_length=255, verbose_name='Cronograma'),
        ),
        migrations.AddField(
            model_name='course',
            name='coDifficulty',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='', max_length=45, verbose_name='Tipo de Dificultad'),
        ),
    ]
