# Generated by Django 3.2.9 on 2022-03-05 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_course_codescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='coInstructor',
            field=models.CharField(default='', max_length=255, verbose_name='Instructor'),
        ),
    ]
