# Generated by Django 3.2.9 on 2022-03-15 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20220314_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='coDifficulty',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=45, verbose_name='Tipo de Dificultad'),
        ),
    ]
