# Generated by Django 3.2.9 on 2022-03-06 02:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monthly_payments', '0001_initial'),
        ('courses', '0003_course_coinstructor'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='monthlyPayment',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='monthly_payments.monthlypayment', verbose_name='Mensualidad'),
        ),
    ]
