# Generated by Django 3.2.9 on 2022-03-06 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_payment_monthlypayment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='monthlyPayment',
        ),
    ]
