# Generated by Django 3.2.9 on 2022-03-06 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_remove_payment_monthlypayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='paDate',
            field=models.DateField(verbose_name='Fecha de Pago'),
        ),
    ]
