# Generated by Django 3.2.9 on 2021-12-16 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol_name', models.CharField(blank=True, choices=[('STUDENT', 'Student'), ('TEACHER', 'Teacher')], help_text='tipo de usuario', max_length=7, null=True)),
            ],
        ),
    ]
