# Generated by Django 3.2.9 on 2022-02-14 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leName', models.CharField(max_length=255, verbose_name='Name')),
                ('leDescription', models.CharField(max_length=255, verbose_name='Description')),
                ('leEvaluation', models.FloatField(verbose_name='Evaluation')),
                ('leLinkVideo', models.CharField(max_length=255, verbose_name='Link Video')),
                ('course', models.ForeignKey(help_text='Lessiones del curso', on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.course', verbose_name='Course')),
            ],
            options={
                'verbose_name': 'Lesson',
                'verbose_name_plural': 'Lessons',
            },
        ),
    ]
