# Generated by Django 3.2.9 on 2022-03-06 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leName', models.CharField(max_length=255, verbose_name='Nombre')),
                ('leDescription', models.CharField(max_length=255, verbose_name='Descripción')),
                ('leEvaluation', models.FloatField(verbose_name='Evaluación')),
                ('leLinkVideo', models.CharField(max_length=255, verbose_name='Link de video')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('course', models.ForeignKey(help_text='Lecciones del curso', on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.course', verbose_name='Curso')),
            ],
            options={
                'verbose_name': 'Leccion',
                'verbose_name_plural': 'Lecciones',
            },
        ),
    ]
