# Generated by Django 3.2.9 on 2022-02-14 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_course_codescription'),
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'verbose_name': 'Leccion', 'verbose_name_plural': 'Lecciones'},
        ),
        migrations.AddField(
            model_name='lesson',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='course',
            field=models.ForeignKey(help_text='Lecciones del curso', on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.course', verbose_name='Curso'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='leDescription',
            field=models.CharField(max_length=255, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='leEvaluation',
            field=models.FloatField(verbose_name='Evaluación'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='leLinkVideo',
            field=models.CharField(max_length=255, verbose_name='Link de video'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='leName',
            field=models.CharField(max_length=255, verbose_name='Nombre'),
        ),
    ]
