# Generated by Django 3.2.9 on 2022-03-15 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_lesson_ledifficulty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='leDifficulty',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=45, verbose_name='Tipo de Dificultad'),
        ),
    ]
